
spring:
  datasource:
    url: jdbc:oracle:thin:@<HOST>:<PORT>/<SERVICE_NAME>
    username: <USERNAME>
    password: <PASSWORD>
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
